spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  thymeleaf:
    cache: false
  jackson:
          date-format: yyyy-MM-dd HH:mm:ss
          time-zone: GMT+8
mybatis:
  type-aliases-package: guet.ty.member.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:logback.xml
server:
  port: 8080
  servlet:
    context-path: /member